import { Component, OnInit } from "@angular/core";

@Component({
  selector: "flx-test",
  templateUrl: "./test.component.html",
  styleUrls: ["./test.component.scss"]
})
export class TestComponent implements OnInit {
  data = [
    { id: 1, name: "A", age: 53, race: "latinoSSS" },
    { id: 2, name: "B", age: 54, race: "mexican-american" },
    {
      id: 1,
      name: "A",
      age: 53,
      race: "latino",
      children: [
        { id: 1, name: "A", age: 53, race: "latino" },
        {
          id: 1,
          name: "A",
          age: 53,
          race: "latino",
          children: [
            { id: 1, name: "A", age: 53, race: "latino" },
            {
              id: 2,
              name: "B",
              age: 54,
              race: "mexican-american"
            },
            {
              id: 1,
              name: "A",
              age: 53,
              race: "latino",
              children: [
                { id: 1, name: "A", age: 53, race: "latino" },
                {
                  id: 2,
                  name: "B",
                  age: 54,
                  race: "mexican-american",
                  children: [{ id: 1, name: "A", age: 53, race: "latino" }]
                },
                {
                  id: 2,
                  name: "B",
                  age: 54,
                  race: "mexican-american"
                },
                { id: 1, name: "A", age: 53, race: "latino" },
                {
                  id: 2,
                  name: "B",
                  age: 54,
                  race: "mexican-american"
                }
              ]
            },
            { id: 1, name: "A", age: 53, race: "latino" }
          ]
        },
        { id: 1, name: "A", age: 53, race: "latino" },
        { id: 1, name: "A", age: 53, race: "latino" }
      ]
    },
    { id: 2, name: "B", age: 54, race: "mexican-american" },
    { id: 1, name: "A", age: 53, race: "latino" },
    { id: 2, name: "B", age: 54, race: "mexican-american" }
  ];

  constructor() {}


  ngOnInit() {}


  spliiice(): void {
    this.data.splice(6, this.data.length-6);
  }


  puuush(): void {
    Array.prototype.push.apply(this.data, [
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" },
      { id: 2, name: "B", age: 54, race: "mexican-american" },
      { id: 1, name: "A", age: 53, race: "latino" }
    ]);
  }
}
